import { PrismaClient, ContentStatus, ClaimStatus, VerificationStatus, FeaturedStatus } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('🏪 Seeding demo businesses...');

  // Get business types
  const foodDining = await prisma.businessType.findUnique({ where: { slug: 'food-dining' } });
  const accommodation = await prisma.businessType.findUnique({ where: { slug: 'accommodation-hospitality' } });
  const retail = await prisma.businessType.findUnique({ where: { slug: 'retail-shopping' } });
  const health = await prisma.businessType.findUnique({ where: { slug: 'health-medical' } });
  const fitness = await prisma.businessType.findUnique({ where: { slug: 'fitness-wellness' } });
  const automotive = await prisma.businessType.findUnique({ where: { slug: 'automotive' } });
  const professional = await prisma.businessType.findUnique({ where: { slug: 'professional-services' } });
  const technology = await prisma.businessType.findUnique({ where: { slug: 'technology-it' } });
  const beauty = await prisma.businessType.findUnique({ where: { slug: 'beauty-personal-care' } });
  const realEstate = await prisma.businessType.findUnique({ where: { slug: 'real-estate-property' } });
  const travel = await prisma.businessType.findUnique({ where: { slug: 'travel-tourism' } });
  const legal = await prisma.businessType.findUnique({ where: { slug: 'legal-services' } });
  const dental = await prisma.businessType.findUnique({ where: { slug: 'dental-oral-health' } });
  const homeProperty = await prisma.businessType.findUnique({ where: { slug: 'home-property-services' } });
  const education = await prisma.businessType.findUnique({ where: { slug: 'education-training' } });
  const pets = await prisma.businessType.findUnique({ where: { slug: 'pets-animals' } });
  const events = await prisma.businessType.findUnique({ where: { slug: 'events-wedding-services' } });

  if (!foodDining || !accommodation || !retail) {
    throw new Error('Required business types not found');
  }

  // Get categories for each type
  const restaurants = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'restaurants', businessTypeId: foodDining.id } } });
  const cafes = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'cafes-coffee-shops', businessTypeId: foodDining.id } } });
  const fastFood = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'fast-food', businessTypeId: foodDining.id } } });
  const hotels = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'hotels-motels', businessTypeId: accommodation.id } } });
  const salons = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'hair-salons', businessTypeId: beauty.id } } });
  const spas = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'spas', businessTypeId: beauty.id } } });
  const gyms = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'gyms-fitness-centers', businessTypeId: fitness.id } } });
  const autoRepair = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'auto-repair', businessTypeId: automotive.id } } });
  const carDealers = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'car-dealers', businessTypeId: automotive.id } } });
  const dentists = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'dentists', businessTypeId: dental.id } } });
  const doctors = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'doctors-physicians', businessTypeId: health.id } } });
  const plumbers = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'plumbing-services', businessTypeId: homeProperty.id } } });
  const electricians = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'electrical-services', businessTypeId: homeProperty.id } } });
  const itConsulting = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'it-consulting', businessTypeId: professional.id } } });
  const softwareDev = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'software-development', businessTypeId: technology.id } } });
  const realEstateAgents = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'real-estate-agents', businessTypeId: realEstate.id } } });
  const travelAgencies = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'travel-agencies', businessTypeId: travel.id } } });
  const lawyers = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'lawyers-attorneys', businessTypeId: legal.id } } });
  const schools = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'schools', businessTypeId: education.id } } });
  const vets = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'veterinarians', businessTypeId: pets.id } } });
  const eventPlanners = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'event-planners', businessTypeId: events.id } } });
  const clothingStores = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'clothing-stores', businessTypeId: retail.id } } });
  const shoeStores = await prisma.category.findUnique({ where: { slug_businessTypeId: { slug: 'shoe-stores', businessTypeId: retail.id } } });

  const businesses = [
    // Food & Dining (8 businesses)
    {
      name: 'The Golden Fork Restaurant',
      slug: 'the-golden-fork-restaurant',
      description: 'A premier fine dining experience featuring contemporary American cuisine with locally sourced ingredients. Our executive chef creates seasonal menus that celebrate the best of regional flavors.',
      shortDescription: 'Fine dining with locally sourced ingredients',
      email: 'reservations@goldenfork.com',
      phone: '(555) 123-4567',
      website: 'https://goldenfork.example.com',
      yearEstablished: 2015,
      priceRange: 4,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'Cash', 'Mobile Pay'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.7,
      reviewCount: 234,
      viewCount: 1560,
      address: '123 Main Street',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postalCode: '10001',
      latitude: 40.7128,
      longitude: -74.006,
      businessTypeId: foodDining.id,
      categoryId: restaurants?.id,
    },
    {
      name: 'Brew & Bean Cafe',
      slug: 'brew-bean-cafe',
      description: 'Your neighborhood coffee shop serving artisan coffee, fresh pastries, and light breakfast options. We partner with local roasters to bring you the finest coffee experience.',
      shortDescription: 'Artisan coffee and fresh pastries',
      email: 'hello@brewandbean.com',
      phone: '(555) 234-5678',
      website: 'https://brewandbean.example.com',
      yearEstablished: 2018,
      priceRange: 2,
      languages: ['English'],
      paymentMethods: ['Credit Card', 'Cash', 'Apple Pay'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.5,
      reviewCount: 156,
      viewCount: 890,
      address: '456 Oak Avenue',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postalCode: '10002',
      latitude: 40.7150,
      longitude: -74.003,
      businessTypeId: foodDining.id,
      categoryId: cafes?.id,
    },
    {
      name: 'Pizza Palace Express',
      slug: 'pizza-palace-express',
      description: 'Fast, fresh, and delicious pizzas made to order. Try our signature hand-tossed crusts and homemade sauce. Delivery available within 5 miles.',
      shortDescription: 'Fast, fresh, made-to-order pizzas',
      email: 'orders@pizzapalace.com',
      phone: '(555) 345-6789',
      website: 'https://pizzapalace.example.com',
      yearEstablished: 2020,
      priceRange: 2,
      languages: ['English', 'Spanish', 'Italian'],
      paymentMethods: ['Credit Card', 'Cash', 'Online Ordering'],
      verificationStatus: VerificationStatus.PENDING,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.2,
      reviewCount: 89,
      viewCount: 567,
      address: '789 Elm Street',
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      postalCode: '90001',
      latitude: 34.0522,
      longitude: -118.2437,
      businessTypeId: foodDining.id,
      categoryId: fastFood?.id,
    },
    {
      name: 'Sakura Japanese Restaurant',
      slug: 'sakura-japanese-restaurant',
      description: 'Authentic Japanese cuisine including sushi, sashimi, and traditional dishes. Our master chef has over 20 years of experience creating exquisite Japanese meals.',
      shortDescription: 'Authentic Japanese cuisine and sushi',
      email: 'info@sakurajapanese.com',
      phone: '(555) 456-7890',
      yearEstablished: 2012,
      priceRange: 4,
      languages: ['English', 'Japanese'],
      paymentMethods: ['Credit Card', 'Cash'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.8,
      reviewCount: 312,
      viewCount: 2100,
      address: '321 Cherry Lane',
      city: 'San Francisco',
      state: 'CA',
      country: 'USA',
      postalCode: '94102',
      latitude: 37.7749,
      longitude: -122.4194,
      businessTypeId: foodDining.id,
      categoryId: restaurants?.id,
    },
    {
      name: 'Taco Fiesta',
      slug: 'taco-fiesta',
      description: 'Vibrant Mexican street food featuring authentic tacos, burritos, and fresh margaritas. Our recipes have been passed down through three generations.',
      shortDescription: 'Authentic Mexican street food',
      email: 'hola@tacofiesta.com',
      phone: '(555) 567-8901',
      yearEstablished: 2019,
      priceRange: 2,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'Cash', 'Venmo'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.4,
      reviewCount: 178,
      viewCount: 980,
      address: '555 Pepper Street',
      city: 'Austin',
      state: 'TX',
      country: 'USA',
      postalCode: '78701',
      latitude: 30.2672,
      longitude: -97.7431,
      businessTypeId: foodDining.id,
      categoryId: fastFood?.id,
    },
    {
      name: 'The Burger Joint',
      slug: 'the-burger-joint',
      description: 'Gourmet burgers made with 100% Angus beef, fresh buns baked daily, and creative toppings. Try our famous truffle fries!',
      shortDescription: 'Gourmet burgers and craft shakes',
      email: 'eat@burgerjoint.com',
      phone: '(555) 678-9012',
      yearEstablished: 2021,
      priceRange: 3,
      languages: ['English'],
      paymentMethods: ['Credit Card', 'Cash', 'Apple Pay', 'Google Pay'],
      verificationStatus: VerificationStatus.PENDING,
      claimedStatus: ClaimStatus.NONE,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.3,
      reviewCount: 67,
      viewCount: 450,
      address: '888 Burger Boulevard',
      city: 'Miami',
      state: 'FL',
      country: 'USA',
      postalCode: '33101',
      latitude: 25.7617,
      longitude: -80.1918,
      businessTypeId: foodDining.id,
      categoryId: fastFood?.id,
    },
    {
      name: 'Mediterranean Breeze',
      slug: 'mediterranean-breeze',
      description: 'Fresh Mediterranean cuisine featuring hummus, falafel, kebabs, and authentic Greek salads. All ingredients are imported directly from the Mediterranean region.',
      shortDescription: 'Fresh Mediterranean and Greek cuisine',
      email: 'welcome@medbreeze.com',
      phone: '(555) 789-0123',
      website: 'https://medbreeze.example.com',
      yearEstablished: 2017,
      priceRange: 3,
      languages: ['English', 'Greek', 'Arabic'],
      paymentMethods: ['Credit Card', 'Cash'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 203,
      viewCount: 1200,
      address: '234 Olive Way',
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      postalCode: '60601',
      latitude: 41.8781,
      longitude: -87.6298,
      businessTypeId: foodDining.id,
      categoryId: restaurants?.id,
    },
    {
      name: 'Pho Saigon',
      slug: 'pho-saigon',
      description: 'Traditional Vietnamese pho and banh mi sandwiches made with family recipes from Saigon. Our broth simmers for 24 hours for maximum flavor.',
      shortDescription: 'Authentic Vietnamese pho and banh mi',
      email: 'pho@saigon.com',
      phone: '(555) 890-1234',
      yearEstablished: 2016,
      priceRange: 2,
      languages: ['English', 'Vietnamese'],
      paymentMethods: ['Cash', 'Credit Card'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.5,
      reviewCount: 145,
      viewCount: 780,
      address: '678 Rice Street',
      city: 'Seattle',
      state: 'WA',
      country: 'USA',
      postalCode: '98101',
      latitude: 47.6062,
      longitude: -122.3321,
      businessTypeId: foodDining.id,
      categoryId: restaurants?.id,
    },

    // Accommodation (4 businesses)
    {
      name: 'Grand Plaza Hotel',
      slug: 'grand-plaza-hotel',
      description: 'Luxury five-star hotel in the heart of downtown featuring 500 rooms, a full-service spa, multiple restaurants, and stunning city views. Perfect for business and leisure travelers.',
      shortDescription: 'Luxury five-star downtown hotel',
      email: 'reservations@grandplaza.com',
      phone: '(555) 111-2222',
      website: 'https://grandplaza.example.com',
      yearEstablished: 2005,
      priceRange: 5,
      languages: ['English', 'Spanish', 'French', 'German'],
      paymentMethods: ['Credit Card', 'Corporate Account', 'Rewards Points'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.9,
      reviewCount: 1567,
      viewCount: 8900,
      address: '100 Grand Plaza Drive',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postalCode: '10003',
      latitude: 40.7282,
      longitude: -73.9942,
      businessTypeId: accommodation.id,
      categoryId: hotels?.id,
    },
    {
      name: 'Cozy Inn Motel',
      slug: 'cozy-inn-motel',
      description: 'Affordable and clean motel offering comfortable rooms for budget-conscious travelers. Free WiFi, parking, and continental breakfast included.',
      shortDescription: 'Affordable and clean motel',
      email: 'stay@cozyinn.com',
      phone: '(555) 222-3333',
      yearEstablished: 1998,
      priceRange: 1,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Cash', 'Credit Card'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 3.8,
      reviewCount: 234,
      viewCount: 1200,
      address: '456 Highway 101',
      city: 'Phoenix',
      state: 'AZ',
      country: 'USA',
      postalCode: '85001',
      latitude: 33.4484,
      longitude: -112.0740,
      businessTypeId: accommodation.id,
      categoryId: hotels?.id,
    },
    {
      name: 'Sunset Beach Resort',
      slug: 'sunset-beach-resort',
      description: 'Beachfront resort with private beach access, oceanfront rooms, water sports, and all-inclusive packages. Experience paradise on the Florida coast.',
      shortDescription: 'Beachfront resort with all-inclusive options',
      email: 'info@sunsetbeach.com',
      phone: '(555) 333-4444',
      website: 'https://sunsetbeach.example.com',
      yearEstablished: 2010,
      priceRange: 4,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'All Inclusive Package'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.7,
      reviewCount: 876,
      viewCount: 5600,
      address: '789 Oceanview Drive',
      city: 'Miami',
      state: 'FL',
      country: 'USA',
      postalCode: '33139',
      latitude: 25.7907,
      longitude: -80.1300,
      businessTypeId: accommodation.id,
      categoryId: hotels?.id,
    },
    {
      name: 'Mountain View Lodge',
      slug: 'mountain-view-lodge',
      description: 'Rustic mountain retreat offering cozy cabins, hiking trails, and breathtaking views. Perfect for outdoor enthusiasts and nature lovers.',
      shortDescription: 'Rustic mountain cabins and outdoor adventure',
      email: 'hello@mountainviewlodge.com',
      phone: '(555) 444-5555',
      yearEstablished: 2015,
      priceRange: 3,
      languages: ['English'],
      paymentMethods: ['Credit Card', 'Cash', 'Check'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 345,
      viewCount: 2100,
      address: '100 Summit Road',
      city: 'Denver',
      state: 'CO',
      country: 'USA',
      postalCode: '80202',
      latitude: 39.7392,
      longitude: -104.9903,
      businessTypeId: accommodation.id,
      categoryId: hotels?.id,
    },

    // Health & Medical (4 businesses)
    {
      name: 'City Medical Center',
      slug: 'city-medical-center',
      description: 'Comprehensive medical facility offering primary care, specialty services, diagnostic imaging, and emergency care. Our team of board-certified physicians is committed to patient-centered care.',
      shortDescription: 'Comprehensive medical care facility',
      email: 'info@citymedical.com',
      phone: '(555) 555-0001',
      website: 'https://citymedical.example.com',
      yearEstablished: 1995,
      priceRange: 4,
      languages: ['English', 'Spanish', 'Mandarin'],
      paymentMethods: ['Insurance', 'Credit Card', 'Payment Plans'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.5,
      reviewCount: 567,
      viewCount: 3400,
      address: '1000 Medical Plaza',
      city: 'Houston',
      state: 'TX',
      country: 'USA',
      postalCode: '77001',
      latitude: 29.7604,
      longitude: -95.3698,
      businessTypeId: health.id,
      categoryId: doctors?.id,
    },
    {
      name: 'Smile Bright Dental',
      slug: 'smile-bright-dental',
      description: 'Family-friendly dental practice offering cleanings, fillings, cosmetic dentistry, and orthodontics. We make going to the dentist a positive experience for all ages.',
      shortDescription: 'Family-friendly dental care',
      email: 'appointments@smiledental.com',
      phone: '(555) 555-0002',
      website: 'https://smilebright.example.com',
      yearEstablished: 2008,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Insurance', 'Credit Card', 'CareCredit'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.8,
      reviewCount: 423,
      viewCount: 2500,
      address: '2500 Dental Way',
      city: 'Dallas',
      state: 'TX',
      country: 'USA',
      postalCode: '75201',
      latitude: 32.7767,
      longitude: -96.7970,
      businessTypeId: dental.id,
      categoryId: dentists?.id,
    },
    {
      name: 'Heartland Family Medicine',
      slug: 'heartland-family-medicine',
      description: 'Compassionate family medicine providing comprehensive healthcare for patients of all ages. We focus on preventive care and building long-term relationships with our patients.',
      shortDescription: 'Compassionate family healthcare',
      email: 'care@heartlandfamily.com',
      phone: '(555) 555-0003',
      yearEstablished: 2010,
      priceRange: 2,
      languages: ['English', 'Hindi', 'Urdu'],
      paymentMethods: ['Insurance', 'Cash', 'Credit Card'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 289,
      viewCount: 1800,
      address: '500 Health Street',
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      postalCode: '60602',
      latitude: 41.8781,
      longitude: -87.6298,
      businessTypeId: health.id,
      categoryId: doctors?.id,
    },
    {
      name: 'Wellness First Clinic',
      slug: 'wellness-first-clinic',
      description: 'Integrative medicine clinic combining conventional and alternative treatments. We address root causes and promote overall wellness through personalized care plans.',
      shortDescription: 'Integrative and wellness medicine',
      email: 'wellness@wellnessfirst.com',
      phone: '(555) 555-0004',
      website: 'https://wellnessfirst.example.com',
      yearEstablished: 2018,
      priceRange: 4,
      languages: ['English'],
      paymentMethods: ['Insurance', 'Credit Card', 'Cash'],
      verificationStatus: VerificationStatus.PENDING,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.4,
      reviewCount: 156,
      viewCount: 980,
      address: '750 Wellness Boulevard',
      city: 'San Diego',
      state: 'CA',
      country: 'USA',
      postalCode: '92101',
      latitude: 32.7157,
      longitude: -117.1611,
      businessTypeId: health.id,
      categoryId: doctors?.id,
    },

    // Beauty & Personal Care (4 businesses)
    {
      name: 'Glamour Studio Salon',
      slug: 'glamour-studio-salon',
      description: 'Full-service hair salon offering cuts, color, styling, and treatments. Our expert stylists stay current with the latest trends and techniques.',
      shortDescription: 'Full-service hair salon',
      email: 'book@glamourstudio.com',
      phone: '(555) 666-0001',
      website: 'https://glamourstudio.example.com',
      yearEstablished: 2014,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'Cash', 'Gift Cards'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.7,
      reviewCount: 345,
      viewCount: 2100,
      address: '400 Fashion Avenue',
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      postalCode: '90015',
      latitude: 34.0386,
      longitude: -118.2613,
      businessTypeId: beauty.id,
      categoryId: salons?.id,
    },
    {
      name: 'Serenity Spa & Wellness',
      slug: 'serenity-spa-wellness',
      description: 'Luxury day spa offering massages, facials, body treatments, and wellness services. Escape the everyday and rejuvenate your mind, body, and spirit.',
      shortDescription: 'Luxury spa and wellness retreat',
      email: 'relax@serenityspa.com',
      phone: '(555) 666-0002',
      website: 'https://serenityspa.example.com',
      yearEstablished: 2016,
      priceRange: 4,
      languages: ['English', 'French', 'Spanish'],
      paymentMethods: ['Credit Card', 'Gift Cards', 'Spa Packages'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.9,
      reviewCount: 567,
      viewCount: 3200,
      address: '200 Tranquil Way',
      city: 'Miami',
      state: 'FL',
      country: 'USA',
      postalCode: '33132',
      latitude: 25.7797,
      longitude: -80.1869,
      businessTypeId: beauty.id,
      categoryId: spas?.id,
    },
    {
      name: 'Style Studio NYC',
      slug: 'style-studio-nyc',
      description: 'Boutique hair salon specializing in precision cuts, balayage, and creative color. Our stylists are trained in the latest European techniques.',
      shortDescription: 'Boutique hair studio',
      email: 'style@stylestudionyc.com',
      phone: '(555) 666-0003',
      yearEstablished: 2019,
      priceRange: 4,
      languages: ['English', 'Italian'],
      paymentMethods: ['Credit Card', 'Venmo'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.8,
      reviewCount: 234,
      viewCount: 1500,
      address: '600 Fifth Avenue',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postalCode: '10019',
      latitude: 40.7580,
      longitude: -73.9855,
      businessTypeId: beauty.id,
      categoryId: salons?.id,
    },
    {
      name: 'Nail Art Gallery',
      slug: 'nail-art-gallery',
      description: 'Trendy nail salon offering manicures, pedicures, nail art, and gel extensions. We use only premium products and maintain strict hygiene standards.',
      shortDescription: 'Trendy nail art and care',
      email: 'nails@nailartgallery.com',
      phone: '(555) 666-0004',
      yearEstablished: 2020,
      priceRange: 2,
      languages: ['English', 'Vietnamese'],
      paymentMethods: ['Cash', 'Credit Card'],
      verificationStatus: VerificationStatus.PENDING,
      claimedStatus: ClaimStatus.NONE,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.3,
      reviewCount: 89,
      viewCount: 560,
      address: '300 Beauty Row',
      city: 'Atlanta',
      state: 'GA',
      country: 'USA',
      postalCode: '30303',
      latitude: 33.7490,
      longitude: -84.3880,
      businessTypeId: beauty.id,
      categoryId: salons?.id,
    },

    // Fitness & Wellness (3 businesses)
    {
      name: 'Iron Pump Gym',
      slug: 'iron-pump-gym',
      description: 'State-of-the-art fitness center with top-of-the-line equipment, personal training, group classes, and 24/7 access. Transform your fitness journey with us.',
      shortDescription: 'State-of-the-art fitness center',
      email: 'join@ironpumpgym.com',
      phone: '(555) 777-0001',
      website: 'https://ironpump.example.com',
      yearEstablished: 2015,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Monthly Membership', 'Annual Membership', 'Credit Card'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.6,
      reviewCount: 456,
      viewCount: 2800,
      address: '1000 Fitness Drive',
      city: 'Austin',
      state: 'TX',
      country: 'USA',
      postalCode: '78701',
      latitude: 30.2849,
      longitude: -97.7341,
      businessTypeId: fitness.id,
      categoryId: gyms?.id,
    },
    {
      name: 'Zen Yoga Studio',
      slug: 'zen-yoga-studio',
      description: 'Peaceful yoga studio offering classes for all levels including vinyasa, hatha, yin, and restorative yoga. Join us to find balance and inner peace.',
      shortDescription: 'Yoga for all levels',
      email: 'practice@zenyoga.com',
      phone: '(555) 777-0002',
      website: 'https://zenyoga.example.com',
      yearEstablished: 2017,
      priceRange: 3,
      languages: ['English', 'Sanskrit'],
      paymentMethods: ['Drop-in Classes', 'Class Packs', 'Membership'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.9,
      reviewCount: 234,
      viewCount: 1600,
      address: '200 Namaste Lane',
      city: 'Portland',
      state: 'OR',
      country: 'USA',
      postalCode: '97201',
      latitude: 45.5152,
      longitude: -122.6784,
      businessTypeId: fitness.id,
      categoryId: gyms?.id,
    },
    {
      name: 'CrossFit Box Downtown',
      slug: 'crossfit-box-downtown',
      description: 'High-intensity functional fitness training in a supportive community. Our certified coaches guide you through challenging workouts scaled to your ability.',
      shortDescription: 'High-intensity functional fitness',
      email: 'wod@crossfitdowntown.com',
      phone: '(555) 777-0003',
      yearEstablished: 2018,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Monthly Membership', 'Drop-in'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.7,
      reviewCount: 178,
      viewCount: 1100,
      address: '500 Barbell Street',
      city: 'Denver',
      state: 'CO',
      country: 'USA',
      postalCode: '80204',
      latitude: 39.7534,
      longitude: -105.0011,
      businessTypeId: fitness.id,
      categoryId: gyms?.id,
    },

    // Automotive (3 businesses)
    {
      name: 'Premium Auto Motors',
      slug: 'premium-auto-motors',
      description: 'Authorized dealer for luxury and performance vehicles. We offer sales, financing, service, and parts for premium automotive brands.',
      shortDescription: 'Luxury automotive dealership',
      email: 'sales@premiumauto.com',
      phone: '(555) 888-0001',
      website: 'https://premiumauto.example.com',
      yearEstablished: 2008,
      priceRange: 5,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Financing', 'Credit Card', 'Cash'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.5,
      reviewCount: 234,
      viewCount: 3400,
      address: '5000 Auto Mall Drive',
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      postalCode: '90210',
      latitude: 34.0901,
      longitude: -118.4065,
      businessTypeId: automotive.id,
      categoryId: carDealers?.id,
    },
    {
      name: 'Quick Fix Auto Repair',
      slug: 'quick-fix-auto-repair',
      description: 'Honest, reliable auto repair and maintenance services. ASE-certified mechanics providing quality service at fair prices. No appointment necessary for most services.',
      shortDescription: 'Honest, reliable auto repair',
      email: 'service@quickfixauto.com',
      phone: '(555) 888-0002',
      yearEstablished: 2012,
      priceRange: 2,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Cash', 'Credit Card', 'Insurance'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 567,
      viewCount: 2900,
      address: '1500 Mechanic Way',
      city: 'Houston',
      state: 'TX',
      country: 'USA',
      postalCode: '77002',
      latitude: 29.7604,
      longitude: -95.3698,
      businessTypeId: automotive.id,
      categoryId: autoRepair?.id,
    },
    {
      name: 'Elite Auto Detail',
      slug: 'elite-auto-detail',
      description: 'Premium auto detailing and ceramic coating services. We bring your vehicle to showroom condition with our professional-grade products and techniques.',
      shortDescription: 'Premium auto detailing',
      email: 'detail@eliteauto.com',
      phone: '(555) 888-0003',
      yearEstablished: 2019,
      priceRange: 3,
      languages: ['English'],
      paymentMethods: ['Credit Card', 'Cash'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.8,
      reviewCount: 156,
      viewCount: 980,
      address: '2500 Shine Street',
      city: 'Miami',
      state: 'FL',
      country: 'USA',
      postalCode: '33130',
      latitude: 25.7617,
      longitude: -80.1918,
      businessTypeId: automotive.id,
      categoryId: autoRepair?.id,
    },

    // Home & Property Services (3 businesses)
    {
      name: 'Swift Plumbing Solutions',
      slug: 'swift-plumbing-solutions',
      description: 'Licensed plumbers available 24/7 for emergency repairs, installations, and maintenance. We specialize in residential and commercial plumbing services.',
      shortDescription: '24/7 licensed plumbing services',
      email: 'help@swiftplumbing.com',
      phone: '(555) 999-0001',
      website: 'https://swiftplumbing.example.com',
      yearEstablished: 2010,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'Cash', 'Insurance'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.7,
      reviewCount: 345,
      viewCount: 2100,
      address: '1000 Pipe Street',
      city: 'Phoenix',
      state: 'AZ',
      country: 'USA',
      postalCode: '85001',
      latitude: 33.4484,
      longitude: -112.0740,
      businessTypeId: homeProperty.id,
      categoryId: plumbers?.id,
    },
    {
      name: 'Bright Spark Electric',
      slug: 'bright-spark-electric',
      description: 'Licensed electrical contractor providing residential and commercial electrical services. From simple repairs to complete rewiring, we do it all safely.',
      shortDescription: 'Licensed electrical services',
      email: 'power@brightspark.com',
      phone: '(555) 999-0002',
      yearEstablished: 2015,
      priceRange: 3,
      languages: ['English'],
      paymentMethods: ['Credit Card', 'Check', 'Financing'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.8,
      reviewCount: 234,
      viewCount: 1500,
      address: '2000 Wire Way',
      city: 'Seattle',
      state: 'WA',
      country: 'USA',
      postalCode: '98101',
      latitude: 47.6062,
      longitude: -122.3321,
      businessTypeId: homeProperty.id,
      categoryId: electricians?.id,
    },
    {
      name: 'Green Thumb Landscaping',
      slug: 'green-thumb-landscaping',
      description: 'Full-service landscaping company offering design, installation, and maintenance. Create the outdoor space of your dreams with our expert team.',
      shortDescription: 'Full-service landscaping design',
      email: 'grow@greenthumb.com',
      phone: '(555) 999-0003',
      website: 'https://greenthumb.example.com',
      yearEstablished: 2013,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'Check', 'Cash'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 189,
      viewCount: 1200,
      address: '3000 Garden Road',
      city: 'San Diego',
      state: 'CA',
      country: 'USA',
      postalCode: '92102',
      latitude: 32.7157,
      longitude: -117.1611,
      businessTypeId: homeProperty.id,
      categoryId: plumbers?.id,
    },

    // Technology (2 businesses)
    {
      name: 'TechCore Solutions',
      slug: 'techcore-solutions',
      description: 'Enterprise IT consulting and software development company. We help businesses transform with custom software, cloud solutions, and digital strategy.',
      shortDescription: 'Enterprise IT and software solutions',
      email: 'info@techcore.com',
      phone: '(555) 101-0001',
      website: 'https://techcore.example.com',
      yearEstablished: 2012,
      priceRange: 4,
      languages: ['English', 'Hindi'],
      paymentMethods: ['Invoice', 'Credit Card'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.8,
      reviewCount: 156,
      viewCount: 2100,
      address: '10000 Tech Park Drive',
      city: 'San Jose',
      state: 'CA',
      country: 'USA',
      postalCode: '95110',
      latitude: 37.3382,
      longitude: -121.8863,
      businessTypeId: technology.id,
      categoryId: itConsulting?.id,
    },
    {
      name: 'ByteForce Software',
      slug: 'byteforce-software',
      description: 'Custom software development for web, mobile, and cloud platforms. Agile methodology and dedicated teams to bring your vision to life.',
      shortDescription: 'Custom software development',
      email: 'build@byteforce.com',
      phone: '(555) 101-0002',
      website: 'https://byteforce.example.com',
      yearEstablished: 2016,
      priceRange: 4,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Fixed Price', 'Time & Materials'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.7,
      reviewCount: 98,
      viewCount: 1300,
      address: '20000 Code Boulevard',
      city: 'Austin',
      state: 'TX',
      country: 'USA',
      postalCode: '78701',
      latitude: 30.2672,
      longitude: -97.7431,
      businessTypeId: technology.id,
      categoryId: softwareDev?.id,
    },

    // Real Estate (2 businesses)
    {
      name: 'Premier Realty Group',
      slug: 'premier-realty-group',
      description: 'Top-producing real estate team specializing in residential and luxury properties. We have a proven track record of closing deals and exceeding client expectations.',
      shortDescription: 'Luxury real estate specialists',
      email: 'homes@premierrealty.com',
      phone: '(555) 202-0001',
      website: 'https://premierrealty.example.com',
      yearEstablished: 2008,
      priceRange: 4,
      languages: ['English', 'Spanish', 'Mandarin'],
      paymentMethods: ['Commission Based'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.9,
      reviewCount: 567,
      viewCount: 4500,
      address: '5000 Homes Boulevard',
      city: 'Miami',
      state: 'FL',
      country: 'USA',
      postalCode: '33131',
      latitude: 25.7617,
      longitude: -80.1918,
      businessTypeId: realEstate.id,
      categoryId: realEstateAgents?.id,
    },
    {
      name: 'Urban Nest Properties',
      slug: 'urban-nest-properties',
      description: 'Boutique real estate brokerage focused on urban living. We help buyers and sellers navigate the city real estate market with expertise and personalized service.',
      shortDescription: 'Urban living real estate experts',
      email: 'find@urbannest.com',
      phone: '(555) 202-0002',
      yearEstablished: 2018,
      priceRange: 3,
      languages: ['English'],
      paymentMethods: ['Commission Based'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 123,
      viewCount: 1800,
      address: '6000 City Living Way',
      city: 'New York',
      state: 'NY',
      country: 'USA',
      postalCode: '10012',
      latitude: 40.7258,
      longitude: -73.9981,
      businessTypeId: realEstate.id,
      categoryId: realEstateAgents?.id,
    },

    // Education (2 businesses)
    {
      name: 'Bright Futures Academy',
      slug: 'bright-futures-academy',
      description: 'Private school offering K-12 education with a focus on STEM and the arts. Our innovative curriculum prepares students for success in a changing world.',
      shortDescription: 'Private K-12 STEM-focused school',
      email: 'admissions@brightfutures.com',
      phone: '(555) 303-0001',
      website: 'https://brightfutures.example.com',
      yearEstablished: 2000,
      priceRange: 4,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Tuition', 'Financial Aid'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.8,
      reviewCount: 234,
      viewCount: 3200,
      address: '100 Education Lane',
      city: 'Boston',
      state: 'MA',
      country: 'USA',
      postalCode: '02101',
      latitude: 42.3601,
      longitude: -71.0589,
      businessTypeId: education.id,
      categoryId: schools?.id,
    },
    {
      name: 'Kumon Learning Center',
      slug: 'kumon-learning-center',
      description: 'After-school tutoring center helping students excel in math and reading. Our proven method builds confidence and academic independence.',
      shortDescription: 'After-school math and reading tutoring',
      email: 'learn@kumoncenter.com',
      phone: '(555) 303-0002',
      yearEstablished: 2015,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Monthly Tuition'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.5,
      reviewCount: 156,
      viewCount: 1900,
      address: '2000 Tutoring Trail',
      city: 'Atlanta',
      state: 'GA',
      country: 'USA',
      postalCode: '30303',
      latitude: 33.7490,
      longitude: -84.3880,
      businessTypeId: education.id,
      categoryId: schools?.id,
    },

    // Pets (2 businesses)
    {
      name: 'Happy Paws Veterinary',
      slug: 'happy-paws-veterinary',
      description: 'Compassionate veterinary care for dogs, cats, and exotic pets. We offer wellness exams, vaccinations, surgery, and emergency services.',
      shortDescription: 'Compassionate veterinary care',
      email: 'care@happypawsvet.com',
      phone: '(555) 404-0001',
      website: 'https://happypaws.example.com',
      yearEstablished: 2010,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'Pet Insurance', 'CareCredit'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.8,
      reviewCount: 345,
      viewCount: 2300,
      address: '1000 Pet Care Lane',
      city: 'Portland',
      state: 'OR',
      country: 'USA',
      postalCode: '97201',
      latitude: 45.5152,
      longitude: -122.6784,
      businessTypeId: pets.id,
      categoryId: vets?.id,
    },
    {
      name: 'Pampered Pets Grooming',
      slug: 'pampered-pets-grooming',
      description: 'Professional pet grooming for dogs and cats. Bathing, haircuts, nail trims, and spa treatments to keep your furry friends looking their best.',
      shortDescription: 'Professional pet grooming',
      email: 'groom@pamperedpets.com',
      phone: '(555) 404-0002',
      yearEstablished: 2017,
      priceRange: 2,
      languages: ['English'],
      paymentMethods: ['Cash', 'Credit Card'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.7,
      reviewCount: 189,
      viewCount: 1200,
      address: '2000 Grooming Street',
      city: 'Seattle',
      state: 'WA',
      country: 'USA',
      postalCode: '98102',
      latitude: 47.6097,
      longitude: -122.3171,
      businessTypeId: pets.id,
      categoryId: vets?.id,
    },

    // Travel (1 business)
    {
      name: 'Wanderlust Travel Agency',
      slug: 'wanderlust-travel-agency',
      description: 'Full-service travel agency creating unforgettable vacation experiences. From beach resorts to adventure tours, we handle every detail.',
      shortDescription: 'Full-service vacation planning',
      email: 'travel@wanderlust.com',
      phone: '(555) 505-0001',
      website: 'https://wanderlust.example.com',
      yearEstablished: 2014,
      priceRange: 3,
      languages: ['English', 'Spanish', 'French'],
      paymentMethods: ['Credit Card', 'Wire Transfer'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 234,
      viewCount: 1600,
      address: '3000 Adventure Avenue',
      city: 'Orlando',
      state: 'FL',
      country: 'USA',
      postalCode: '32801',
      latitude: 28.5383,
      longitude: -81.3792,
      businessTypeId: travel.id,
      categoryId: travelAgencies?.id,
    },

    // Legal (1 business)
    {
      name: 'Justice & Associates Law Firm',
      slug: 'justice-associates-law-firm',
      description: 'Experienced attorneys practicing in family law, business law, and personal injury. We fight for your rights with dedication and integrity.',
      shortDescription: 'Family, business, and injury law',
      email: 'legal@justiceassociates.com',
      phone: '(555) 606-0001',
      website: 'https://justiceassociates.example.com',
      yearEstablished: 2005,
      priceRange: 4,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Hourly Rate', 'Contingency', 'Flat Fee'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.7,
      reviewCount: 156,
      viewCount: 1900,
      address: '4000 Justice Plaza',
      city: 'Washington',
      state: 'DC',
      country: 'USA',
      postalCode: '20001',
      latitude: 38.9072,
      longitude: -77.0369,
      businessTypeId: legal.id,
      categoryId: lawyers?.id,
    },

    // Events (1 business)
    {
      name: 'Memorable Events Co.',
      slug: 'memorable-events-co',
      description: 'Professional event planning for weddings, corporate events, and celebrations. We bring your vision to life with creativity and flawless execution.',
      shortDescription: 'Wedding and event planning',
      email: 'events@memorableevents.com',
      phone: '(555) 707-0001',
      website: 'https://memorableevents.example.com',
      yearEstablished: 2016,
      priceRange: 4,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Planning Retainer', 'Credit Card'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.FEATURED,
      rating: 4.9,
      reviewCount: 234,
      viewCount: 2800,
      address: '5000 Celebration Court',
      city: 'Las Vegas',
      state: 'NV',
      country: 'USA',
      postalCode: '89101',
      latitude: 36.1699,
      longitude: -115.1398,
      businessTypeId: events.id,
      categoryId: eventPlanners?.id,
    },

    // Retail (2 businesses)
    {
      name: 'Fashion Forward Boutique',
      slug: 'fashion-forward-boutique',
      description: 'Curated fashion boutique featuring emerging designers and sustainable fashion. Find unique pieces that express your individual style.',
      shortDescription: 'Curated sustainable fashion',
      email: 'shop@fashionforward.com',
      phone: '(555) 808-0001',
      website: 'https://fashionforward.example.com',
      yearEstablished: 2018,
      priceRange: 4,
      languages: ['English'],
      paymentMethods: ['Credit Card', 'Apple Pay'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.6,
      reviewCount: 123,
      viewCount: 1500,
      address: '6000 Style Street',
      city: 'Los Angeles',
      state: 'CA',
      country: 'USA',
      postalCode: '90028',
      latitude: 34.0928,
      longitude: -118.3287,
      businessTypeId: retail.id,
      categoryId: clothingStores?.id,
    },
    {
      name: 'Stride Comfort Shoes',
      slug: 'stride-comfort-shoes',
      description: 'Specialty shoe store focused on comfort and quality. Expert fitting services for walking, running, and everyday comfort footwear.',
      shortDescription: 'Comfort footwear specialists',
      email: 'fit@stridecomfort.com',
      phone: '(555) 808-0002',
      yearEstablished: 2012,
      priceRange: 3,
      languages: ['English', 'Spanish'],
      paymentMethods: ['Credit Card', 'Cash'],
      verificationStatus: VerificationStatus.VERIFIED,
      claimedStatus: ClaimStatus.CLAIMED,
      featuredStatus: FeaturedStatus.NONE,
      rating: 4.7,
      reviewCount: 189,
      viewCount: 1200,
      address: '7000 Walking Way',
      city: 'Denver',
      state: 'CO',
      country: 'USA',
      postalCode: '80202',
      latitude: 39.7534,
      longitude: -105.0011,
      businessTypeId: retail.id,
      categoryId: shoeStores?.id,
    },
  ];

  // Insert all businesses
  for (const business of businesses) {
    await prisma.business.upsert({
      where: { slug: business.slug },
      update: {},
      create: business,
    });
  }

  console.log(`✅ Created ${businesses.length} demo businesses`);
  console.log('\n📋 Demo businesses added:');
  businesses.forEach(b => console.log(`   - ${b.name} (${b.city}, ${b.state})`));
}

main()
  .catch((e) => {
    console.error('Error seeding businesses:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
